#!/usr/bin/env python3
"""Emit netclasses into 04_kicad/xt60-usb-supply.kicad_pro and width floors
into 04_kicad/xt60-usb-supply.kicad_dru from 03_src/rules/nets.yaml.

MUST run LAST in the rebuild chain: pcbnew saves clobber .kicad_pro
netclasses (skill empiric, 2026-07-16). Merges the .kicad_pro (never
rewrites wholesale); the .kicad_dru is fully generated and deterministic.

DRC width comparisons are EXACT NANOMETERS — all emitted values are clean
decimals.
"""
import json
import re
import sys
from pathlib import Path

PROJ = Path(__file__).resolve().parent.parent
BOARD = "xt60-usb-supply"
KICAD = PROJ / "04_kicad"

# JLC 4-layer STANDARD tier floors (drc-discipline.md, 2026 numbers)
FAB = {
    "min_clearance": 0.1,
    "min_track_width": 0.09,
    "min_via_diameter": 0.45,
    "min_through_hole_diameter": 0.2,
    "min_via_annular_width": 0.125,   # (0.45-0.2)/2
    "min_hole_clearance": 0.2,
    "min_hole_to_hole": 0.2,
    "min_copper_edge_clearance": 0.2,
}


def parse_nets_yaml(path):
    """Minimal YAML subset parser for our nets.yaml (no external deps on
    the KiCad-bundled python). Extracts classes: {name: {nets, min_width}}.
    A parse yielding zero classes is an ERROR (contract)."""
    classes = {}
    cur = None
    in_classes = False
    for raw in path.read_text().splitlines():
        line = raw.split("#", 1)[0].rstrip() if not raw.lstrip().startswith("#") else ""
        if not line:
            continue
        if line == "classes:":
            in_classes = True
            continue
        if not in_classes:
            continue
        m = re.match(r"^  (\w+):\s*$", line)
        if m:
            cur = m.group(1)
            classes[cur] = {"nets": [], "min_width": None}
            continue
        if cur is None:
            continue
        m = re.match(r"^    nets:\s*\[(.*)\]\s*$", line)
        if m:
            classes[cur]["nets"] = [n.strip() for n in m.group(1).split(",") if n.strip()]
            continue
        m = re.match(r"^    min_width:\s*([0-9.]+)mm\s*$", line)
        if m:
            classes[cur]["min_width"] = float(m.group(1))
            continue
    if not classes:
        raise SystemExit("ERROR: parsed zero classes from nets.yaml")
    for name, c in classes.items():
        if not c["nets"] or c["min_width"] is None:
            raise SystemExit(f"ERROR: class {name} missing nets or min_width")
    return classes


def netclass_entry(name, min_width):
    return {
        "bus_width": 12,
        "clearance": 0.1,
        "diff_pair_gap": 0.25,
        "diff_pair_via_gap": 0.25,
        "diff_pair_width": 0.2,
        "line_style": 0,
        "microvia_diameter": 0.3,
        "microvia_drill": 0.1,
        "name": name,
        "pcb_color": "rgba(0, 0, 0, 0.000)",
        "priority": 2147483647,
        "schematic_color": "rgba(0, 0, 0, 0.000)",
        "track_width": max(min_width, 0.2),
        "via_diameter": 0.6,
        "via_drill": 0.3,
        "wire_width": 6,
    }


def merge_pro(classes):
    pro_path = KICAD / f"{BOARD}.kicad_pro"
    pro = json.loads(pro_path.read_text()) if pro_path.exists() else {}
    ns = pro.setdefault("net_settings", {})
    existing = [c for c in ns.get("classes", []) if c.get("name") == "Default"]
    if not existing:
        d = netclass_entry("Default", 0.2)
        d["track_width"] = 0.2
        existing = [d]
    for name, c in sorted(classes.items()):
        existing.append(netclass_entry(name, c["min_width"]))
    ns["classes"] = existing
    ns.setdefault("meta", {"version": 4})
    ns["net_colors"] = None
    ns["netclass_assignments"] = None
    patterns = []
    for name, c in sorted(classes.items()):
        for net in c["nets"]:
            patterns.append({"netclass": name, "pattern": net})
    ns["netclass_patterns"] = patterns

    board = pro.setdefault("board", {})
    ds = board.setdefault("design_settings", {})
    rules = ds.setdefault("rules", {})
    rules.update(FAB)
    # severity policy: generated board is source of truth for lib checks
    sev = ds.setdefault("rule_severities", {})
    sev.update({
        "lib_footprint_issues": "ignore",
        "lib_footprint_mismatch": "ignore",
    })
    pro.setdefault("meta", {"filename": f"{BOARD}.kicad_pro", "version": 3})
    pro_path.write_text(json.dumps(pro, indent=2, sort_keys=True) + "\n")
    return pro_path


def write_dru(classes):
    dru_path = KICAD / f"{BOARD}.kicad_dru"
    lines = ["(version 1)", ""]
    lines += [
        "# GENERATED by 03_src/generate_rules.py from 03_src/rules/nets.yaml.",
        "# Never hand-edit; edit nets.yaml and regenerate.",
        "",
    ]
    for name, c in sorted(classes.items()):
        w = f"{c['min_width']:g}mm"
        lines += [
            f'(rule "width_{name.lower()}"',
            f'  (condition "A.NetClass == \'{name}\'")',
            f"  (constraint track_width (min {w})))",
            "",
        ]
    # unnetted mechanical pads (connector pegs, shields) are exempt from
    # copper clearance-to-anything-same-position noise
    lines += [
        '(rule "unnetted mechanical pads exempt"',
        '  (condition "A.NetName == \'\'")',
        "  (constraint clearance (min 0mm)))",
        "",
    ]
    dru_path.write_text("\n".join(lines))
    return dru_path


def main():
    classes = parse_nets_yaml(PROJ / "03_src" / "rules" / "nets.yaml")
    KICAD.mkdir(exist_ok=True)
    p = merge_pro(classes)
    d = write_dru(classes)
    print(f"RULES: wrote {d.name} + merged {p.name}: "
          f"{len(classes)} classes, floors {FAB['min_track_width']}/{FAB['min_clearance']}")


if __name__ == "__main__":
    main()
