M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu24.04.1 date 2026-07-27T17:05:34
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-27T17:05:34-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X22.46Y-20.0
X22.46Y-46.0
T2
X14.0Y-14.0
X14.0Y-52.0
X60.0Y-14.0
X60.0Y-52.0
M30
