M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu24.04.1 date 2026-08-01T17:24:00
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-01T17:24:00-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X24.0Y-24.0
X24.0Y-106.0
X146.0Y-72.0
X146.0Y-106.0
M30
