M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu24.04.1 date 2026-07-19T19:20:08
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-19T19:20:08-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X37.0Y-138.0
T2
X24.0Y-24.0
X24.0Y-110.5
X24.0Y-136.0
X126.0Y-124.0
X201.0Y-24.5
X201.0Y-136.0
M30
