M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu24.04.1 date 2026-07-27T20:08:10
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-27T20:08:10-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.770
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X66.15Y-89.2
X81.85Y-89.2
T2
X17.0Y-90.0
X24.0Y-14.0
X193.0Y-52.0
X194.0Y-14.0
M30
