M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu24.04.1 date 2026-07-23T12:37:48
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-23T12:37:48-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X117.11Y-106.4
X122.89Y-106.4
T2
X61.675Y-58.0
X70.325Y-58.0
T3
X26.0Y-26.0
X26.0Y-106.0
X106.0Y-24.0
X144.0Y-92.0
M30
