#!/usr/bin/env python3
"""Emit netclasses (-> .kicad_pro) and width floors (-> .kicad_dru) from
rules/nets.yaml. THE generated files must never be hand-edited (src/contracts.md).
Run after generate_schematic.py (which creates the .kicad_pro)."""
import json, re, sys
from pathlib import Path
try:
    import yaml
except ImportError:
    sys.exit("needs pyyaml (python3 -m pip install pyyaml)")

HERE = Path(__file__).parent
K = HERE.parent / "kicad"
BOARD = "usb_power_3s"
cfg = yaml.safe_load(open(HERE / "rules" / "nets.yaml"))

def mm(v): return float(str(v).replace("mm", ""))

pro_path = K / f"{BOARD}.kicad_pro"
if not pro_path.exists():
    sys.exit(f"{pro_path} missing - run generate_schematic.py first")
pro = json.load(open(pro_path))
ns = pro.setdefault("net_settings", {"classes": [{"name": "Default",
    "clearance": 0.10, "track_width": 0.2, "via_diameter": 0.6,
    "via_drill": 0.3, "microvia_diameter": 0.3, "microvia_drill": 0.1,
    "diff_pair_width": 0.2, "diff_pair_gap": 0.25, "diff_pair_via_gap": 0.25,
    "bus_width": 12, "line_style": 0, "pcb_color": "rgba(0, 0, 0, 0.000)",
    "schematic_color": "rgba(0, 0, 0, 0.000)", "wire_width": 6}]})
base = next(c for c in ns["classes"] if c["name"] == "Default")
classes, pats = [base], []
for name, c in cfg["classes"].items():
    d = dict(base); d["name"] = name
    d["track_width"] = max(mm(c["min_width"]) * 2, 0.3)  # routing default, not the floor
    d["clearance"] = 0.10
    classes.append(d)
    for net in c["nets"]:
        pats.append({"netclass": name, "pattern": net})
ns["classes"] = classes
ns["netclass_patterns"] = pats
for c in pro.get("net_settings", {}).get("classes", []):
    if c.get("name") == "Default":
        c["clearance"] = 0.10
bds = pro.setdefault("board", {}).setdefault("design_settings", {})
bds.setdefault("rules", {}).update({
    "min_clearance": 0.09, "min_track_width": 0.09,
    "min_via_diameter": 0.25, "min_through_hole_diameter": 0.15,
    "min_via_annular_width": 0.045, "min_hole_clearance": 0.125,
    "min_hole_to_hole": 0.1, "min_copper_edge_clearance": 0.1,
    "min_connection": 0.09, "min_microvia_diameter": 0.2,
    "min_microvia_drill": 0.1, "min_resolved_spokes": 1,
    "min_silk_clearance": 0.0, "min_text_height": 0.6,
    "min_text_thickness": 0.08, "max_error": 0.005,
    "solder_mask_to_copper_clearance": 0.0, "use_height_for_length_calcs": True})
json.dump(pro, open(pro_path, "w"), indent=2)

dru = [f"(version 1)\n# GENERATED by generate_rules.py from rules/nets.yaml - DO NOT HAND-EDIT"]
for name, c in cfg["classes"].items():
    dru.append(f"(rule width_{name.lower()}\n  (condition \"A.NetClass == '{name}'\")\n"
               f"  (constraint track_width (min {mm(c['min_width']):.2f}mm)))")
    for ex in c.get("exemptions", []):
        dru.append(f"(rule width_{name.lower()}_{ex['area'].lower()}\n"
                   f"  (condition \"A.NetClass == '{name}' && A.intersectsArea('{ex['area']}')\")\n"
                   f"  (constraint track_width (min {mm(ex['min_width']):.2f}mm)))")
(K / f"{BOARD}.kicad_dru").write_text("\n".join(dru) + "\n")
print(f"netclasses: {[c['name'] for c in classes]}; {len(pats)} patterns; dru rules written")
