M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu24.04.1 date 2026-07-23T20:13:53
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-23T20:13:53-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.770
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X66.15Y-89.2
X81.85Y-89.2
T2
X19.0Y-97.0
X27.0Y-15.0
X253.0Y-15.0
X257.0Y-97.0
M30
