#!/usr/bin/env python3
"""Emit netclasses (-> .kicad_pro) and width/isolation floors (-> .kicad_dru)
from rules/nets.yaml. Runs LAST in the rebuild chain (pcbnew saves clobber
.kicad_pro netclasses) AND before route-prep (canon R1).

4-layer JLC standard tier: 0.6/0.3 vias. The iso_keypad DRU rule is the
machine form of §6.3/§8.4: KEYPAD-class copper >= 6mm from every other net.
"""
import json
import sys
from pathlib import Path
try:
    import yaml
except ImportError:
    sys.exit("needs pyyaml")

HERE = Path(__file__).parent
K = HERE.parent / "04_kicad"
BOARD = "cook_hub"
cfg = yaml.safe_load(open(HERE / "rules" / "nets.yaml"))


def mm(v):
    return float(str(v).replace("mm", ""))


pro_path = K / f"{BOARD}.kicad_pro"
if not pro_path.exists():
    sys.exit(f"{pro_path} missing - run generate_schematic.py first")
pro = json.load(open(pro_path))
ns = pro.setdefault("net_settings", {"classes": [{"name": "Default",
    "clearance": 0.127, "track_width": 0.2, "via_diameter": 0.6,
    "via_drill": 0.3, "microvia_diameter": 0.3, "microvia_drill": 0.1,
    "diff_pair_width": 0.2, "diff_pair_gap": 0.2, "diff_pair_via_gap": 0.2,
    "bus_width": 12, "line_style": 0, "pcb_color": "rgba(0, 0, 0, 0.000)",
    "schematic_color": "rgba(0, 0, 0, 0.000)", "wire_width": 6}]})
base = next(c for c in ns["classes"] if c["name"] == "Default")
base["track_width"] = 0.2
base["via_diameter"] = 0.6
base["via_drill"] = 0.3
classes, pats = [base], []
for name, c in cfg["classes"].items():
    d = dict(base)
    d["name"] = name
    d["track_width"] = max(mm(c["min_width"]), 0.2)
    classes.append(d)
    for net in c["nets"]:
        pats.append({"netclass": name, "pattern": net})
for c in classes:
    c["clearance"] = 0.127
ns["classes"] = classes
ns["netclass_patterns"] = pats
bds = pro.setdefault("board", {}).setdefault("design_settings", {})
bds.setdefault("rules", {}).update({
    "min_clearance": 0.127, "min_track_width": 0.15,
    "min_via_diameter": 0.45, "min_through_hole_diameter": 0.2,
    "min_via_annular_width": 0.13, "min_hole_clearance": 0.25,
    "min_hole_to_hole": 0.5, "min_copper_edge_clearance": 0.3,
    "min_connection": 0.127, "min_microvia_diameter": 0.2,
    "min_microvia_drill": 0.1, "min_resolved_spokes": 1,
    "min_silk_clearance": 0.0, "min_text_height": 0.6,
    "min_text_thickness": 0.08, "max_error": 0.005,
    "solder_mask_to_copper_clearance": 0.0, "use_height_for_length_calcs": True})
json.dump(pro, open(pro_path, "w"), indent=2)

dru = ["(version 1)\n# GENERATED by generate_rules.py from rules/nets.yaml - DO NOT HAND-EDIT"]
for name, c in cfg["classes"].items():
    dru.append(f"(rule width_{name.lower()}\n  (condition \"A.NetClass == '{name}'\")\n"
               f"  (constraint track_width (min {mm(c['min_width']):.2f}mm)))")
# THE isolation rule (§6.3/§8.4): keypad copper >= 6mm from all other nets
dru.append("(rule iso_keypad\n"
           "  (condition \"A.NetClass == 'KEYPAD' && B.NetClass != 'KEYPAD'\")\n"
           "  (constraint clearance (min 6.00mm)))")
# ---- courtyard-overlap waivers (evidence-backed, golden rule 8) ----------
# Every pair below is an INTENTIONAL placement-density overlap of COURTYARDS
# only (pad/body bboxes do NOT overlap; pre-route audit I-checks + screw
# keepouts pass). Categories:
#  * coil test point under its relay body (ADR-0002/D15: TP41-56 probe the
#    coil nets straight south of pin 7, deliberately beneath the DIP relay);
#  * decoupler tight to its IC (canon 7 snap-back: C8/C12/C13/C14 at U3/U4/U7);
#  * ESD/opto tight to its connector/neighbour (U10/U11/U13/U14 at J*/U5);
#  * small part under the Pico socket footprint (module sits on the header
#    stack above C21/R23/SW1);
#  * courtyard graze of adjacent connectors / a mounting-hole ring (H1/H5).
# The ONE real overlap (H6 mounting hole on J13 pads) was FIXED by relocating
# H6 (geom.HOLES), not waived. KiCad 10 only honours '==' in DRU conditions
# ('=~' regex is a no-op here), so each pair is emitted explicitly.
COURTYARD_WAIVERS = [
    ("K1", "TP41"), ("K2", "TP41"), ("K2", "TP42"), ("K3", "TP43"),
    ("K4", "TP43"), ("K4", "TP44"), ("K5", "TP45"), ("K6", "TP45"),
    ("K6", "TP46"), ("K7", "TP47"), ("K8", "TP47"), ("K8", "TP48"),
    ("K9", "TP49"), ("K10", "TP49"), ("K10", "TP50"), ("K11", "TP51"),
    ("K12", "TP51"), ("K12", "TP52"), ("K13", "TP53"), ("K14", "TP53"),
    ("K14", "TP54"), ("K15", "TP55"), ("K16", "TP55"), ("K16", "TP56"),
    ("C12", "U3"), ("C13", "U4"), ("C14", "U7"), ("C8", "U7"), ("Q1", "U7"),
    ("J14", "U14"), ("J3", "U13"), ("J4", "U14"), ("J2", "U14"),
    ("U10", "U11"), ("U11", "U5"), ("CE1", "D2"),
    ("C21", "J2"), ("J2", "R23"), ("J2", "SW1"),
    ("J3", "J5"), ("C6", "H1"), ("FB1", "H1"), ("H5", "R52"),
]
for i, (a, c) in enumerate(COURTYARD_WAIVERS):
    dru.append(f"(rule cy_waive_{i}\n"
               f"  (condition \"(A.Reference == '{a}' && B.Reference == '{c}') || "
               f"(A.Reference == '{c}' && B.Reference == '{a}')\")\n"
               f"  (constraint courtyard_clearance (min -6mm)))")

(K / f"{BOARD}.kicad_dru").write_text("\n".join(dru) + "\n")
print(f"netclasses: {[c['name'] for c in classes]}; {len(pats)} patterns; "
      f"dru width rules + iso_keypad 6mm + {len(COURTYARD_WAIVERS)} "
      f"courtyard waivers written")
