M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu24.04.1 date 2026-08-13T21:20:46
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-13T21:20:46-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X62.11Y-78.72
X67.89Y-78.72
T2
X25.0Y-25.0
X25.0Y-80.0
X105.0Y-25.0
X105.0Y-80.0
M30
