#!/usr/bin/env python3
"""Emit netclasses (-> .kicad_pro) and width floors (-> .kicad_dru) from
rules/nets.yaml. Runs LAST in the rebuild chain (pcbnew saves clobber
.kicad_pro netclasses) AND before route-prep (canon R1).

2-layer JLC default tier: 0.6/0.3 vias, 0.2/0.127 track/clearance floors.
"""
import json
import sys
from pathlib import Path
try:
    import yaml
except ImportError:
    sys.exit("needs pyyaml")

HERE = Path(__file__).parent
K = HERE.parent / "04_kicad"
BOARD = "cook_loadcell"
cfg = yaml.safe_load(open(HERE / "rules" / "nets.yaml"))


def mm(v):
    return float(str(v).replace("mm", ""))


pro_path = K / f"{BOARD}.kicad_pro"
if not pro_path.exists():
    sys.exit(f"{pro_path} missing - run generate_schematic.py first")
pro = json.load(open(pro_path))
ns = pro.setdefault("net_settings", {"classes": []})
if not ns.get("classes"):
    ns["classes"] = [{"name": "Default"}]
base = next(c for c in ns["classes"] if c["name"] == "Default")
base.update({"clearance": 0.127, "track_width": 0.25, "via_diameter": 0.6,
             "via_drill": 0.3, "microvia_diameter": 0.3, "microvia_drill": 0.1,
             "diff_pair_width": 0.2, "diff_pair_gap": 0.2,
             "diff_pair_via_gap": 0.2, "bus_width": 12, "line_style": 0,
             "pcb_color": "rgba(0, 0, 0, 0.000)",
             "schematic_color": "rgba(0, 0, 0, 0.000)", "wire_width": 6})
classes, pats = [base], []
for name, c in cfg["classes"].items():
    d = dict(base)
    d["name"] = name
    d["track_width"] = max(mm(c["min_width"]), 0.25)
    classes.append(d)
    for net in c["nets"]:
        pats.append({"netclass": name, "pattern": net})
ns["classes"] = classes
ns["netclass_patterns"] = pats
bds = pro.setdefault("board", {}).setdefault("design_settings", {})
bds.setdefault("rules", {}).update({
    "min_clearance": 0.127, "min_track_width": 0.2,
    "min_via_diameter": 0.45, "min_through_hole_diameter": 0.2,
    "min_via_annular_width": 0.13, "min_hole_clearance": 0.25,
    "min_hole_to_hole": 0.5, "min_copper_edge_clearance": 0.3,
    "min_connection": 0.127, "min_microvia_diameter": 0.2,
    "min_microvia_drill": 0.1, "min_resolved_spokes": 1,
    "min_silk_clearance": 0.0, "min_text_height": 0.6,
    "min_text_thickness": 0.08, "max_error": 0.005,
    "solder_mask_to_copper_clearance": 0.0,
    "use_height_for_length_calcs": True})
json.dump(pro, open(pro_path, "w"), indent=2)

dru = ["(version 1)",
       "# GENERATED by generate_rules.py from rules/nets.yaml - DO NOT HAND-EDIT"]
for name, c in cfg["classes"].items():
    dru.append(f"(rule width_{name.lower()}\n"
               f"  (condition \"A.NetClass == '{name}'\")\n"
               f"  (constraint track_width (min {mm(c['min_width']):.2f}mm)))")
(K / f"{BOARD}.kicad_dru").write_text("\n".join(dru) + "\n")
print(f"netclasses: {[c['name'] for c in classes]}; {len(pats)} patterns; "
      f"dru width rules written")
