M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu24.04.1 date 2026-07-18T23:41:38
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-18T23:41:38-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X56.6Y-81.11
X56.6Y-86.89
T2
X52.3Y-93.0
X80.2Y-52.6
X211.0Y-52.8
X211.0Y-111.2
M30
