M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu24.04.1 date 2026-08-15T15:13:20
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-15T15:13:20-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X25.0Y-25.0
X75.0Y-135.0
X100.0Y-136.0
X165.0Y-25.0
M30
