#!/usr/bin/env python3
"""Export a readable, refdes-only assembly/rework drawing.

The production board is never edited.  A temporary copy is used to move the
F.Fab ${REFERENCE} fields away from the two dense component clusters.  KiCad
then supplies the actual component outlines and board geometry.  The output is
an overview followed by vector zooms of the switch and module-control areas.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import pcbnew


# Absolute board coordinates in mm.  Only the drawing-only ${REFERENCE} text
# is moved.  The alternating columns keep long identifiers clear of one
# another while leaving the component bodies visible in the detail views.
REF_POSITIONS = {
    "R_PD1": (35.0, 49.0),
    "R_PD2": (35.0, 52.0),
    "C_SW1": (48.0, 49.0),
    "R_PD3": (35.0, 55.0),
    "R_PD4": (48.0, 55.0),
    "C_SW2": (41.6, 59.0),
    "LED_ST": (36.0, 78.2),
    "R_LED": (42.0, 78.2),
    "R_S4": (48.0, 83.29),
    "R_S3": (48.0, 85.83),
    "R_S2": (48.0, 88.37),
    "R_S1": (48.0, 90.91),
    "C_BULK": (69.5, 82.75),
    "FB_3V3": (69.5, 85.80),
}

# Crop boxes are PDF points in the board-area-only A4 overview generated by
# KiCad 10.  They intentionally include surrounding connectors/module outline
# so a rework technician can orient each enlarged detail on the overview.
DETAIL_CROPS = (
    ("switch", (315, 235, 485, 420)),
    ("module", (345, 35, 620, 225)),
)


def run(args: list[str]) -> None:
    subprocess.run(args, check=True)


def prepare_drawing_board(source: Path, output: Path) -> None:
    board = pcbnew.LoadBoard(str(source))
    refs_seen: set[str] = set()

    drawing_text = {}
    for item in board.GetDrawings():
        if isinstance(item, pcbnew.PCB_TEXT) and item.GetLayer() == pcbnew.F_Fab:
            drawing_text.setdefault(item.GetText(), []).append(item)

    for footprint in board.GetFootprints():
        ref = footprint.GetReference()
        # Library footprints are inconsistent here: stock passives carry a
        # ${REFERENCE} Fab text while the project SMA/module footprints do not.
        # Blank any library copies and reuse the one board-level label emitted
        # by the generic board generator.  --exclude-refdes suppresses the
        # ordinary footprint field.  This avoids both zero-label custom
        # footprints and two-label stock footprints.
        for item in footprint.GraphicalItems():
            if (
                hasattr(item, "GetText")
                and "${REFERENCE}" in item.GetText()
                and item.GetLayer() == pcbnew.F_Fab
            ):
                item.SetText("")

        candidates = drawing_text.get(ref, [])
        if len(candidates) != 1:
            raise RuntimeError(
                f"{ref}: expected exactly one board-level F.Fab label, "
                f"found {len(candidates)}"
            )
        text = candidates[0]
        text.SetTextSize(pcbnew.VECTOR2I_MM(0.8, 0.8))
        text.SetTextThickness(pcbnew.FromMM(0.12))
        text.SetTextAngle(pcbnew.EDA_ANGLE(0, pcbnew.DEGREES_T))
        x_mm, y_mm = REF_POSITIONS.get(
            ref,
            (
                pcbnew.ToMM(footprint.GetPosition().x),
                pcbnew.ToMM(footprint.GetPosition().y),
            ),
        )
        text.SetPosition(pcbnew.VECTOR2I_MM(x_mm, y_mm))
        refs_seen.add(ref)

    unknown = set(REF_POSITIONS) - refs_seen
    if unknown:
        raise RuntimeError(f"assembly refdes layout names missing footprints: {sorted(unknown)}")

    pcbnew.SaveBoard(str(output), board)


def crop_and_fit(source: Path, crop: tuple[int, int, int, int], output: Path) -> None:
    with tempfile.TemporaryDirectory(prefix="rx2-v4-assembly-crop-") as td:
        cropped = Path(td) / "cropped.pdf"
        llx, lly, urx, ury = crop
        run(
            [
                "gs",
                "-q",
                "-dBATCH",
                "-dNOPAUSE",
                "-sDEVICE=pdfwrite",
                "-o",
                str(cropped),
                "-c",
                f"[/CropBox [{llx} {lly} {urx} {ury}] /PAGES pdfmark",
                "-f",
                str(source),
            ]
        )
        run(
            [
                "gs",
                "-q",
                "-dBATCH",
                "-dNOPAUSE",
                "-sDEVICE=pdfwrite",
                "-dFIXEDMEDIA",
                "-dPDFFitPage",
                "-dDEVICEWIDTHPOINTS=841.896",
                "-dDEVICEHEIGHTPOINTS=595.296",
                "-dUseCropBox",
                "-o",
                str(output),
                str(cropped),
            ]
        )


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {Path(sys.argv[0]).name} INPUT.kicad_pcb OUTPUT.pdf", file=sys.stderr)
        return 2

    source = Path(sys.argv[1]).resolve()
    output = Path(sys.argv[2]).resolve()
    if not source.is_file():
        raise FileNotFoundError(source)
    output.parent.mkdir(parents=True, exist_ok=True)

    for tool in ("kicad-cli", "gs", "pdfunite"):
        if shutil.which(tool) is None:
            raise RuntimeError(f"required assembly-drawing tool is missing: {tool}")

    with tempfile.TemporaryDirectory(prefix="rx2-v4-assembly-") as td:
        work = Path(td)
        drawing_board = work / source.name
        overview = work / "overview.pdf"
        prepare_drawing_board(source, drawing_board)

        # Values and ordinary reference properties are excluded.  The single
        # relocated ${REFERENCE} field in each footprint is the sole label.
        # Omitting --sketch-pads-on-fab-layers avoids pad-number clutter while
        # retaining every F.Fab body outline and Edge.Cuts geometry.
        run(
            [
                "kicad-cli",
                "pcb",
                "export",
                "pdf",
                "--mode-single",
                "-l",
                "F.Fab,Edge.Cuts",
                "--exclude-refdes",
                "--exclude-value",
                "--black-and-white",
                "--no-property-popups",
                "--scale",
                "0",
                "-o",
                str(overview),
                str(drawing_board),
            ]
        )

        pages = [overview]
        for name, crop in DETAIL_CROPS:
            detail = work / f"detail-{name}.pdf"
            crop_and_fit(overview, crop, detail)
            pages.append(detail)

        assembled = work / "assembly.pdf"
        run(["pdfunite", *(str(page) for page in pages), str(assembled)])
        shutil.copyfile(assembled, output)

    print(f"Assembly drawing: {output} (overview + 2 vector details)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
