M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu24.04.1 date 2026-07-18T09:29:58
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-18T09:29:58-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X56.8Y-92.11
X56.8Y-97.89
T2
X55.5Y-55.5
X55.5Y-119.5
X174.5Y-55.5
X174.5Y-119.5
M30
