M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu24.04.1 date 2026-08-12T06:49:33
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-12T06:49:33-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X112.11Y-103.72
X117.89Y-103.72
T2
X25.0Y-25.0
X25.0Y-105.0
X134.8Y-25.0
X145.0Y-105.0
M30
