#!/usr/bin/env python3
"""Generate or verify MCU/decoder timing artifacts from one control contract."""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

from control_protocol_check import ProtocolError, grade, load


def project_path(project: Path, raw: str, label: str) -> Path:
    path = (project / raw).resolve()
    try:
        path.relative_to(project)
    except ValueError as exc:
        raise ProtocolError(f"{label} must remain inside project: {raw}") from exc
    return path


def outputs(project: Path, data: dict, contract: Path) -> tuple[Path, str, Path, str]:
    profile = data.get("profile")
    if not isinstance(profile, dict):
        raise ProtocolError("code generation requires schema-2 profile metadata")
    header = project_path(project, profile["firmware_header"],
                          "profile.firmware_header")
    decoder = project_path(project, profile["decoder_json"],
                           "profile.decoder_json")
    if header.suffix.lower() != ".h":
        raise ProtocolError("profile.firmware_header must name a .h file")
    if decoder.suffix.lower() != ".json":
        raise ProtocolError("profile.decoder_json must name a .json file")
    targets = (contract.resolve(), header, decoder)
    aliases = any(
        left.exists() and right.exists() and left.samefile(right)
        for index, left in enumerate(targets)
        for right in targets[index + 1:]
    )
    if len(set(targets)) != 3 or aliases:
        raise ProtocolError(
            "profile output paths must be distinct and must not overwrite "
            "the source contract")
    order = data["frame"]["order"]
    states = data["states"]
    marker = data["frame"]["marker"]
    digest = hashlib.sha256(contract.read_bytes()).hexdigest()
    rows = []
    decoder_states = []
    for name in order:
        state = states[name]
        code = state["gpio_PA3_PA2_PA1_PA0"]
        dwell = state["dwell_ms"]
        low, high = state["window_ms"]
        rows.append(f'  {{ 0x{int(code, 2):X}u, {dwell}u }}, /* {name} */')
        decoder_states.append({
            "name": name,
            "gpio_code_pa3_pa0": code,
            "dwell_ms": dwell,
            "window_ms": [low, high],
        })
    header_text = f"""/* GENERATED by control_profile_codegen.py; do not edit. */
#ifndef PLUTO_CONTROL_PROFILE_H
#define PLUTO_CONTROL_PROFILE_H
#include <stdint.h>

#define CONTROL_PROFILE_ID \"{profile['id']}\"
#define CONTROL_PROFILE_REVISION {profile['revision']}u
#define CONTROL_PROFILE_CONTRACT_SHA256 \"{digest}\"
#define CONTROL_ALL_OFF_CODE 0x{int(states['ALL_OFF']['gpio_PA3_PA2_PA1_PA0'], 2):X}u
#define CONTROL_GUARD_MS {data['frame']['all_off_guard_ms']}u
#define CONTROL_MARKER_BODY_MS {marker['body_nominal_ms']}u
#define CONTROL_STATE_COUNT {len(order)}u
#define CONTROL_NOMINAL_CYCLE_MS {data['frame']['nominal_cycle_ms']}u

typedef struct {{ uint8_t gpio_code_pa3_pa0; uint16_t dwell_ms; }} control_step_t;
static const control_step_t CONTROL_SCHEDULE[CONTROL_STATE_COUNT] = {{
{chr(10).join(rows)}
}};

#endif
"""
    decoder_doc = {
        "schema": 1,
        "generated_from": profile["source_of_truth"],
        "contract_sha256": digest,
        "profile": {"id": profile["id"], "revision": profile["revision"]},
        "protocol": data["protocol"],
        "clock": data["clock"],
        "states": decoder_states,
        "frame": data["frame"],
        "decoder": data["decoder"],
    }
    decoder_text = json.dumps(decoder_doc, indent=2, sort_keys=True) + "\n"
    return header, header_text, decoder, decoder_text


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project")
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", action="store_true")
    action.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    project = Path(args.project).resolve()
    contract = project / "03_src/rules/control_protocol.yaml"
    try:
        data = load(contract)
        failures, summary = grade(data)
        if failures:
            for failure in failures:
                print(f"CONTROL-PROFILE FAIL: {failure}")
            return 1
        header, header_text, decoder, decoder_text = outputs(
            project, data, contract)
    except (OSError, KeyError, TypeError, ValueError, ProtocolError) as exc:
        print(f"CONTROL-PROFILE LOAD ERROR: {exc}")
        return 2

    expected = ((header, header_text), (decoder, decoder_text))
    print(f"input: {contract}")
    print("CONTROL-PROFILE coverage: 2/2 generated consumer artifact(s) graded")
    if args.write:
        for path, content in expected:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        print(f"CONTROL-PROFILE WRITE: {summary['profile_id']} r"
              f"{summary['profile_revision']}; 2/2 artifacts written")
        return 0

    stale = []
    for path, content in expected:
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            stale.append(path.relative_to(project).as_posix())
    if stale:
        print("CONTROL-PROFILE STALE: " + ", ".join(stale))
        print("run control_profile_codegen.py <project> --write")
        return 1
    print(f"CONTROL-PROFILE PASS: {summary['profile_id']} r"
          f"{summary['profile_revision']}; 2/2 artifacts exact")
    return 0


if __name__ == "__main__":
    sys.exit(main())
