#!/usr/bin/env python3
"""Emit netclasses (-> .kicad_pro) and width floors (-> .kicad_dru) from
rules/nets.yaml. Generated files must never be hand-edited (03_src/contracts.md).
Runs LAST in the rebuild chain (pcbnew saves clobber .kicad_pro netclasses)
AND before route-prep (canon R1: rules ride into the router).
4-layer JLC STANDARD tier (ADR-0001): 0.45/0.3 vias, 0.127 track/space floor."""
import json
import sys
from pathlib import Path
try:
    import yaml
except ImportError:
    sys.exit("needs pyyaml (python3 -m pip install pyyaml)")

HERE = Path(__file__).parent
K = HERE.parent / "04_kicad"
BOARD = "crow_array_central"
cfg = yaml.safe_load(open(HERE / "rules" / "nets.yaml"))


def mm(v):
    return float(str(v).replace("mm", ""))


pro_path = K / f"{BOARD}.kicad_pro"
if not pro_path.exists():
    sys.exit(f"{pro_path} missing - run generate_schematic.py first")
pro = json.load(open(pro_path))
ns = pro.setdefault("net_settings", {"classes": [{"name": "Default",
    "clearance": 0.15, "track_width": 0.25, "via_diameter": 0.6,
    "via_drill": 0.3, "microvia_diameter": 0.3, "microvia_drill": 0.1,
    "diff_pair_width": 0.25, "diff_pair_gap": 0.25, "diff_pair_via_gap": 0.25,
    "bus_width": 12, "line_style": 0, "pcb_color": "rgba(0, 0, 0, 0.000)",
    "schematic_color": "rgba(0, 0, 0, 0.000)", "wire_width": 6}]})
base = next(c for c in ns["classes"] if c["name"] == "Default")
classes, pats = [base], []
for name, c in cfg["classes"].items():
    d = dict(base)
    d["name"] = name
    d["track_width"] = max(mm(c["min_width"]), 0.25)
    classes.append(d)
    for net in c["nets"]:
        pats.append({"netclass": name, "pattern": net})
for c in classes:
    # D20: JLC 6L standard capability clearance floor = 0.09mm (3.5mil)
    # (drc-discipline.md capability table; fab page authoritative over the
    # conservative 0.127 default). The 0.4mm-pitch XU316 escapes grade to
    # ~0.11 and the 0.127 netclass floor false-failed ~21 manufacturable-
    # margin items (all actual >= 0.09). Router still targets 0.15 nominal.
    c["clearance"] = 0.09
ns["classes"] = classes
ns["netclass_patterns"] = pats
bds = pro.setdefault("board", {}).setdefault("design_settings", {})
bds.setdefault("rules", {}).update({
    # D20: JLC 6L standard capability floors (drc-discipline.md table; the
    # fab capability page is authoritative over conservative defaults).
    # clearance/track 0.09; via 0.45/0.25 (drill floor 0.25 allows JLC 6L
    # min via drill); hole-to-hole 0.5 (JLC center-to-center); edge 0.2.
    "min_clearance": 0.09, "min_track_width": 0.09,
    # ADR-0009: fine-pitch escape uses the JLC 6L SMALL-VIA option. min via
    # 0.30/0.15 (0.075mm annular): the 0.4mm-pitch XU316 via-in-pad escapes
    # need <0.45mm dia (0.45 shorts the adjacent TDO/TDI pair + encroaches
    # neighbour pads). The task's own 0.25-drill floor already invoked this
    # sub-0.30-drill option; 0.15 is JLC's small-via minimum. Bulk grid/
    # service vias stay 0.6/0.3 standard; only the escape needs the option.
    "min_via_diameter": 0.30, "min_through_hole_diameter": 0.15,
    "min_via_annular_width": 0.05, "min_hole_clearance": 0.2,
    # D20: hole-to-hole = JLC 6L via-to-via capability 0.2mm (KiCad measures
    # EDGE-to-edge; JLC's ~0.5mm quote is CENTRE-to-centre = 0.2mm edge for
    # our 0.3mm-drill vias). The prior 0.5mm-EDGE floor demanded 0.8mm centre
    # spacing and false-failed 13 diff-pair/adjacent escape vias (all 0.39-
    # 0.48mm edge, i.e. 0.69-0.78mm centre) that JLC 6L builds routinely.
    "min_hole_to_hole": 0.2, "min_copper_edge_clearance": 0.2,
    "min_connection": 0.1, "min_microvia_diameter": 0.2,
    "min_microvia_drill": 0.1, "min_resolved_spokes": 1,
    "min_silk_clearance": 0.0, "min_text_height": 0.6,
    "min_text_thickness": 0.08, "max_error": 0.005,
    "solder_mask_to_copper_clearance": 0.0, "use_height_for_length_calcs": True})
json.dump(pro, open(pro_path, "w"), indent=2)

dru = ["(version 1)\n# GENERATED by generate_rules.py from rules/nets.yaml - DO NOT HAND-EDIT"]
# Footprint-intrinsic NPTH pegs: connector mounting/NPTH pads sit at a
# vendor-fixed distance from the connector's own GND/shield pads (J12 USB-C
# shield pads are 0.125mm from its NPTH pegs). This is the connector's own
# land pattern, not a routing choice - JLC builds it as the datasheet draws
# it. Scope hole_clearance for the netless NPTH pad to 0.1mm (evidence in
# 03_src/rules/policy_waivers.yaml). Different-net copper still gets 0.2mm.
dru.append("(rule npth_peg_intrinsic\n"
           "  (condition \"A.Type == 'Pad' && A.NetName == ''\")\n"
           "  (constraint hole_clearance (min 0.1mm)))")
for name, c in cfg["classes"].items():
    w = mm(c["min_width"])
    if name in ("RAIL", "PWR5"):
        # power keeps its ampacity floor OUTSIDE the XU316 tap area, but the
        # short per-pin IO taps inside it may neck to 0.15 (D19 / rule area).
        dru.append(f"(rule width_{name.lower()}\n"
                   f"  (condition \"A.NetClass == '{name}' && !A.insideArea('xu316_taps')\")\n"
                   f"  (constraint track_width (min {w:.2f}mm)))")
        dru.append(f"(rule width_{name.lower()}_tap\n"
                   f"  (condition \"A.NetClass == '{name}' && A.insideArea('xu316_taps')\")\n"
                   f"  (constraint track_width (min 0.15mm)))")
    else:
        dru.append(f"(rule width_{name.lower()}\n  (condition \"A.NetClass == '{name}'\")\n"
                   f"  (constraint track_width (min {w:.2f}mm)))")
(K / f"{BOARD}.kicad_dru").write_text("\n".join(dru) + "\n")
print(f"netclasses: {[c['name'] for c in classes]}; {len(pats)} patterns; dru rules written")
