#!/usr/bin/env python3
"""Emit netclasses (-> .kicad_pro) and width floors (-> .kicad_dru) from
rules/nets.yaml. Generated files must never be hand-edited (03_src/contracts.md).
Runs BEFORE route-prep (canon R1: rules ride into the router) AND LAST in
the rebuild chain (pcbnew saves clobber .kicad_pro netclasses).

JLC 2-layer 2oz tier (verified 2026-07-18, jlcpcb.com/capabilities):
min track/space 0.16/0.16mm, SMD pad-pad (different nets) 0.15mm — the
0.5mm-pitch INA238/USB-C pads (0.15/0.20mm gaps) are legal. Netclass
clearance is 0.15 so the fine-pitch pads pass; routed clearances are
enforced by construction (KRT --clearance 0.2, hand geometry >=0.16).

The KELVIN exception (ADR-0002): PORT-class tracks are floored at 3.0mm
(tripwire — power rides pours), EXCEPT inside the rule areas named
KELVIN where the shunt sense taps run at 0.40mm. Later rules take
precedence in KiCad DRC, so the exception comes last."""
import json
import sys
from pathlib import Path
try:
    import yaml
except ImportError:
    sys.exit("needs pyyaml (python3 -m pip install pyyaml)")

HERE = Path(__file__).parent
K = HERE.parent / "04_kicad"
BOARD = "ble_bus_bar"
cfg = yaml.safe_load(open(HERE / "rules" / "nets.yaml"))


def mm(v):
    return float(str(v).replace("mm", ""))


pro_path = K / f"{BOARD}.kicad_pro"
if not pro_path.exists():
    sys.exit(f"{pro_path} missing - run generate_schematic.py first")
pro = json.load(open(pro_path))
ns = pro.setdefault("net_settings", {"classes": [{"name": "Default",
    "clearance": 0.15, "track_width": 0.3, "via_diameter": 0.6,
    "via_drill": 0.3, "microvia_diameter": 0.3, "microvia_drill": 0.1,
    "diff_pair_width": 0.25, "diff_pair_gap": 0.25, "diff_pair_via_gap": 0.25,
    "bus_width": 12, "line_style": 0, "pcb_color": "rgba(0, 0, 0, 0.000)",
    "schematic_color": "rgba(0, 0, 0, 0.000)", "wire_width": 6}]})
base = next(c for c in ns["classes"] if c["name"] == "Default")
base["track_width"] = 0.3
classes, pats = [base], []
for name, c in cfg["classes"].items():
    d = dict(base)
    d["name"] = name
    d["track_width"] = max(mm(c["min_width"]), 0.3)
    classes.append(d)
    for net in c["nets"]:
        pats.append({"netclass": name, "pattern": net})
for c in classes:
    c["clearance"] = 0.15  # fine-pitch pad-pad floor; routing clears 0.2+
ns["classes"] = classes
ns["netclass_patterns"] = pats
bds = pro.setdefault("board", {}).setdefault("design_settings", {})
bds.setdefault("rules", {}).update({
    "min_clearance": 0.15, "min_track_width": 0.16,
    "min_via_diameter": 0.3, "min_through_hole_diameter": 0.2,
    "min_via_annular_width": 0.05, "min_hole_clearance": 0.2,
    "min_hole_to_hole": 0.25, "min_copper_edge_clearance": 0.2,
    "min_connection": 0.05, "min_microvia_diameter": 0.2,
    "min_microvia_drill": 0.1, "min_resolved_spokes": 1,
    "min_silk_clearance": 0.0, "min_text_height": 0.5,
    "min_text_thickness": 0.08, "max_error": 0.005,
    "solder_mask_to_copper_clearance": 0.0, "solder_mask_min_width": 0.0,
    "use_height_for_length_calcs": True})
json.dump(pro, open(pro_path, "w"), indent=2)

dru = ["(version 1)\n# GENERATED by generate_rules.py from rules/nets.yaml - DO NOT HAND-EDIT"]
for name, c in cfg["classes"].items():
    dru.append(f"(rule width_{name.lower()}\n  (condition \"A.NetClass == '{name}'\")\n"
               f"  (constraint track_width (min {mm(c['min_width']):.2f}mm)))")
# KELVIN exception LAST (later rules win): sense taps at 0.40mm inside the
# named rule areas at each shunt (ADR-0002/0003)
dru.append("(rule width_port_kelvin\n"
           "  (condition \"A.NetClass == 'PORT' && A.intersectsArea('KELVIN')\")\n"
           "  (constraint track_width (min 0.40mm)))")
(K / f"{BOARD}.kicad_dru").write_text("\n".join(dru) + "\n")
print(f"netclasses: {[c['name'] for c in classes]}; {len(pats)} patterns; dru rules written")
